export const CHALLENGE_PRESETS = [
  {
    id: 'no-spend-week',
    name: 'No-Spend Week',
    type: 'no-spend',
    durationDays: 7,
    targetAmount: 0,
    description: 'Zero non-essential spending for 7 days.',
    emoji: '🚫',
    allowedCategories: ['Housing & Rent', 'Bills & Utilities', 'Healthcare', 'Family & Support'],
  },
  {
    id: 'save-500',
    name: 'Save ₱500 This Week',
    type: 'save-amount',
    durationDays: 7,
    targetAmount: 500,
    description: 'Add ₱500 to savings within 7 days.',
    emoji: '💰',
  },
  {
    id: 'save-1000',
    name: 'Save ₱1,000 This Month',
    type: 'save-amount',
    durationDays: 30,
    targetAmount: 1000,
    description: 'Reach ₱1,000 in savings contributions this month.',
    emoji: '🏦',
  },
  {
    id: 'streak-30',
    name: '30-Day Savings Streak',
    type: 'streak',
    durationDays: 30,
    targetAmount: 0,
    description: 'Log at least one savings transaction every day for 30 days.',
    emoji: '🔥',
  },
  {
    id: 'under-budget',
    name: 'Under Budget This Month',
    type: 'under-budget',
    durationDays: 30,
    targetAmount: 0,
    description: 'Stay under your budget limits for a full period.',
    emoji: '📊',
  },
  {
    id: 'no-dining-week',
    name: 'Cook at Home Week',
    type: 'no-spend',
    durationDays: 7,
    targetAmount: 0,
    description: 'No spending on restaurants or food delivery for 7 days.',
    emoji: '🍳',
    allowedCategories: ['Housing & Rent', 'Bills & Utilities', 'Healthcare', 'Family & Support', 'Transportation', 'Subscriptions'],
    targetCategory: 'Food & Dining',
  },
  {
    id: 'no-shopping-fortnight',
    name: 'No Impulse Buys',
    type: 'no-spend',
    durationDays: 14,
    targetAmount: 0,
    description: 'No shopping or clothing purchases for 14 days. Needs only.',
    emoji: '🛍️',
    allowedCategories: ['Housing & Rent', 'Bills & Utilities', 'Healthcare', 'Family & Support', 'Transportation', 'Food & Dining', 'Subscriptions'],
    targetCategory: 'Shopping & Clothing',
  },
  {
    id: 'no-grab-fortnight',
    name: 'Public Transport Only',
    type: 'no-spend',
    durationDays: 14,
    targetAmount: 0,
    description: 'Skip ride-hailing apps for 14 days. Commute the thrifty way.',
    emoji: '🚌',
    allowedCategories: ['Housing & Rent', 'Bills & Utilities', 'Healthcare', 'Family & Support', 'Food & Dining', 'Shopping & Clothing', 'Subscriptions'],
    targetCategory: 'Transportation',
  },
  {
    id: 'no-entertainment-week',
    name: 'No Extras Week',
    type: 'no-spend',
    durationDays: 7,
    targetAmount: 0,
    description: 'Pause entertainment and leisure spending for 7 days.',
    emoji: '📵',
    allowedCategories: ['Housing & Rent', 'Bills & Utilities', 'Healthcare', 'Family & Support', 'Transportation', 'Food & Dining'],
    targetCategory: 'Entertainment',
  },
  {
    id: 'payday-saver-14',
    name: 'Payday Saver',
    type: 'save-amount',
    durationDays: 14,
    targetAmount: 1000,
    description: 'Save ₱1,000 within your 14-day pay period. Pay yourself first.',
    emoji: '💼',
  },
  {
    id: 'semi-monthly-budget',
    name: 'Stay Under Budget (2 Weeks)',
    type: 'under-budget',
    durationDays: 14,
    targetAmount: 0,
    description: 'Keep all spending under your budget limits for one full pay period.',
    emoji: '📋',
  },
  {
    id: 'streak-14',
    name: '14-Day Savings Streak',
    type: 'streak',
    durationDays: 14,
    targetAmount: 0,
    description: 'Log at least one savings transaction every day for 14 days.',
    emoji: '⚡',
  },
  {
    id: 'save-2500-fortnight',
    name: 'Save ₱2,500 This Pay Period',
    type: 'save-amount',
    durationDays: 14,
    targetAmount: 2500,
    description: 'Challenge yourself to save ₱2,500 before your next paycheck.',
    emoji: '🎯',
  },
]
