export const CHALLENGE_PRESETS = [
  {
    id: 'no-spend-week',
    name: 'No-Spend Week',
    type: 'no-spend',
    durationDays: 7,
    targetAmount: 0,
    description: 'Zero non-essential spending for 7 days.',
    emoji: '🚫',
    allowedCategories: ['Housing & Rent', 'Bills & Utilities', 'Healthcare', 'Family & Support'],
  },
  {
    id: 'save-500',
    name: 'Save ₱500 This Week',
    type: 'save-amount',
    durationDays: 7,
    targetAmount: 500,
    description: 'Add ₱500 to savings within 7 days.',
    emoji: '💰',
  },
  {
    id: 'save-1000',
    name: 'Save ₱1,000 This Month',
    type: 'save-amount',
    durationDays: 30,
    targetAmount: 1000,
    description: 'Reach ₱1,000 in savings contributions this month.',
    emoji: '🏦',
  },
  {
    id: 'streak-30',
    name: '30-Day Savings Streak',
    type: 'streak',
    durationDays: 30,
    targetAmount: 0,
    description: 'Log at least one savings transaction every day for 30 days.',
    emoji: '🔥',
  },
  {
    id: 'under-budget',
    name: 'Under Budget This Month',
    type: 'under-budget',
    durationDays: 30,
    targetAmount: 0,
    description: 'Stay under your budget limits for a full period.',
    emoji: '📊',
  },
  {
    id: 'no-dining-week',
    name: 'Cook at Home Week',
    type: 'no-spend',
    durationDays: 7,
    targetAmount: 0,
    description: 'No spending on restaurants or food delivery for 7 days.',
    emoji: '🍳',
    allowedCategories: ['Housing & Rent', 'Bills & Utilities', 'Healthcare', 'Family & Support', 'Transportation', 'Subscriptions'],
    targetCategory: 'Food & Dining',
  },
]
